<a href="https://colab.research.google.com/github/Whenning42/Affinity/blob/master/linear_algebra_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# William’s Linear Algebra Notes

## Latex Background

An latex command is given between two `$` symbols. For example `$m \times n$` renders as $m \times n$.

Here's a table of some common notation:

| Name  | Rendered | Latex |
|-------|--------------|------------|
| Reals | $\mathbb{R}$ | \mathbb{R} |
| Complex | $\mathbb{C}$ | \mathbb{C} |
| Exponentiation | $a^b$, $a^{b+c}$ | a^b, a^{b+c}, note to put more than a letter in the exponent, we use curly brackets. |
| Transpose | $A^\top$ | A^\top |
| Dot Product | $x \cdot y$ | x \cdot y |

## Matrices

A matrix is an $m \times n$ rectangle consisting of $m$ rows and $n$ columns of scalar values from some field $\mathbb{F}$ (commonly $\mathbb{R}$ or $\mathbb{C}$). We deonte the space of $m \times n$ matrices as $\mathbb{F}^{m \times n}$.

An example $2 \times 3$ matrix $A$ over the reals is:
$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$

### Latex

We use $\text{\begin{bmatrix}}$ and $\text{\end{bmatrix}}$ to create a bracketted matrix. So to render the above matrix, we write:

```
A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}
```

In [ ]:
import numpy as np
import torch
import jax.numpy as jnp

# Note: All libraries use row major notation.
# Sets a to:
# [[1, 2, 3]
#  [4, 5, 6]]
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(a)

a = jnp.array([[1, 2, 3], [4, 5, 6]])
print(a)

# TODO: Add some simple matrix constructors like eye or diag.

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
[[1 2 3]
 [4 5 6]]


## Block Matrices

A block matrix is a matrix that concatenates a rectangular grid of submatrices. Block matrices are denoted as:

$M = \begin{bmatrix} A & B \\ C & D \end{bmatrix}$

With concatenated matrices needing to match the size of their neighbors along their adjacent sides.

In [ ]:
# Numpy
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = np.block([[a, b], [c, d]])
print(M)

# Torch
#
# Torch doesn't have a block matrix constructor.
# We can however use `torch.cat().
a = torch.tensor(a)
b = torch.tensor(b)
c = torch.tensor(c)
d = torch.tensor(d)
t = torch.cat([a, b], dim=1)
b = torch.cat([c, d], dim=1)
M = torch.cat([t, b], dim = 0)
print(M)

# Jax
a = np.array([[2]])
b = np.array([[4, 6]])
c = np.array([[8]])
d = np.array([[10, 12]])
M = jnp.block([[a, b], [c, d]])
print(M)


[[ 2  4  6]
 [ 8 10 12]]
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
[[ 2  4  6]
 [ 8 10 12]]


## Matrix Transpose

The transpose of a matrix $A$ is denoted as $A^\top$ and is the result of flipping that matrix across its diagonal.

Formally $A^\top$ is defined such that $A^\top_{j,i} = A_{i,j} \ \forall i, j$.

### Latex

We use `^\top` to indicate the transpose, so for example `A^\top` gives us $A^\top$.

In [ ]:
# A transpose can be applied in both the Numpy and Torch APIs either
# by reordering axes or swapping two axes. We show both options for
# both APIs. Do note the APIs use different names for these operations.

# Numpy
# `np.transpose` reorders axes.
# `np.swapaxes()` swaps two axes.
a = np.array([[1, 2]])
print(np.transpose(a, axes=(1, 0)))
print(np.swapaxes(a, 0, 1))


# Torch
# `torch.permute` reorders axes.
# `torch.swapaxes()` swaps two axes.
a = torch.Tensor([[1,  2]])
print(torch.permute(a, (1, 0)))
print(torch.transpose(a, 0, 1))

# Jax
a = jnp.array([[1, 2]])
print(jnp.transpose(a, (1, 0)))
print(jnp.swapaxes(a, 0, 1))

The transpose of [[1 2]] is:
[[1]
 [2]]
[[1]
 [2]]
tensor([[1.],
        [2.]])
tensor([[1.],
        [2.]])
[[1]
 [2]]
[[1]
 [2]]


## Matrix Multiplication

The product matrices $A$ and $B$ of size $m \times n$ and $n \times k$ respectively is denoted $AB$ and it's a matrix of size $m \times k$ where:

$AB_{ij} = A_i \cdot B_{:,j}$

In [60]:
# Note: Both numpy and torch use the `*` operator on matrices to be an
# elementwise product, not a matrix multiply.
a = np.array([[1, 5], [2, 6]])
b = np.array([[1, 0], [0, 2]])
print("A\n", a)
print("B\n", b)
print("AB")

# Numpy
# A matrix multiply can be performed with `np.matmul()`, the `@` operator, or an
# einsum.
print(a @ b)
print(np.matmul(a, b))
print(np.einsum('ij,jk->ik', a, b))

# Torch
a = torch.tensor(a)
b = torch.tensor(b)
print(a @ b)
print(torch.matmul(a, b))
print(torch.einsum('ij,jk->ik', a, b))

# Do note that Numpy's einsum is much slower that matmul since it's a python
# implementation whereas Torch and Jax's einsum are close in speed to
# their matmuls.
a = np.ones((500, 500))
b = np.ones((500, 500))
print("Numpy matmul vs einsum:")
%timeit np.matmul(a, b)
%timeit np.einsum('ij,jk->ik', a, b)
a = torch.tensor(a)
b = torch.tensor(b)
print("Torch matmul vs einsum:")
%timeit torch.matmul(a, b)
%timeit torch.einsum('ij,jk->ik', a, b)


A
 [[1 5]
 [2 6]]
B
 [[1 0]
 [0 2]]
AB
[[ 1 10]
 [ 2 12]]
[[ 1 10]
 [ 2 12]]
[[ 1 10]
 [ 2 12]]
tensor([[ 1, 10],
        [ 2, 12]])
tensor([[ 1, 10],
        [ 2, 12]])
tensor([[ 1, 10],
        [ 2, 12]])
Numpy matmul vs einsum:
11.3 ms ± 2.63 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
134 ms ± 40.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Torch matmul vs einsum:
18.8 ms ± 4.49 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
9.95 ms ± 2.41 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


TODO:
- add batching to our examples?
  - I'm not sure which of the functions in this notebook would might be non-obvious in terms of how they generalize to batched matrices.
- vec op
- invertability
- orthonormal matrices
- angle between vectors
- determinant
- eigenvalues
- eigenvectors
- trace
- chapter 2 exercises?